fix: fix weird & invalid md format
armbian/documentation pull request #198
Opened 2022-03-29 13:16 UTC by littlecxm

fix: fix weird & invalid md format

2022-03-29 16:47 UTC, EvilOlaf requested changes

2022-03-29 16:47 UTC, EvilOlaf commented on docs/Community_IRC.md
> -- **ArmbianGithub**
This is the actual name of the bot.

2022-03-29 17:04 UTC, littlecxm commented on docs/Community_IRC.md
> -- **Armbian-Discord**
sorry change it back

2022-04-04 21:46 UTC, igorpecovnik commented
> okay and i suggest the better way is publish binary pdf to release through CI

Yes. This would be nice to refactor some day.

2022-04-05 03:04 UTC, littlecxm commented
> > okay and i suggest the better way is publish binary pdf to release through CI
> 
> Yes. This would be nice to refactor some day. https://armbian.atlassian.net/browse/AR-1147

https://github.com/armbian/documentation/pull/199

2022-04-05 06:36 UTC, merged